### PR TITLE
Adds support for SRID.

### PR DESCRIPTION
**Pull request by sikhlana**
This PR adds full support of MySQL's SRID by implementing a simple EWKB parser on top of what is currently being used. More information can be found here: https://github.com/grimzy/laravel-mysql-spatial/issues/54#issuecomment-552051020

### CODE REVIEW

**Comment by sikhlana** [comment]
Do note that this PR bumps the MySQL version to 8.0 since older versions do not have or have minimal support for SRID.

**Comment by sikhlana** [comment]
And the minimum Laravel version if 5.6 since SRID support for schema blueprint is available from then on.

**Comment by denkurbatov** [comment]
Is it any news for when this PR will be merged to master?

Thanks in advance.

**Comment by sikhlana** [comment]
@denkurbatov do note that there are a few caveats with this PR including a database-level one on how the latitude and longitude is saved as EWKB. I have been using this version on my production server and had to rebuild the spatial fields as **SRID 4326** requires you to set the first value as latitude and the second as longitude in MySQL 8.0.

**Comment by grimzy** [comment]
Thank you @sikhlana!

Sorry for taking such a long time to look at this. 

This article explains a lot about this PR: https://mysqlserverteam.com/axis-order-in-spatial-reference-systems/

I also understand we have to start a `mysql-5.7` branch because unfortunately there's no backward compatibility. (`master` will be for MySQL 8)
So release `v3.0.0` will be for MySQL 8 and SRID support; the `2.*` versions  will be for MySQL 5.7 only.

With MySQL 8's WKT now defaulting to `srid-defined`, it feels weird inserting `long-lat + axis-order=long-lat` instead of just inserting `lat-long` or let the users decide. (I'll ticket this)

Regarding the migrations VS Laravel 5.6, I believe [this commit](https://github.com/grimzy/laravel-mysql-spatial/pull/111/commits/4db0a4a212def2083e1bef733414c57c30c1e72d) and maybe one more change to `Grimzy\LaravelMysqlSpatial\Schema\Grammars\MySqlGrammar` (+ fix tests) add what's needed for Laravel 5.2+ MySQL 8.
I'd rather not drop compatibility for older versions of Laravel and PHP until Laravel completely does ([Aug 30th, 2020](https://laravel-news.com/laravel-release-process)).

I'll be merging this with the `srid` branch and work on releasing `v3`.

Thanks again @sikhlana!

**Pull request merged**
