### PR TITLE
fix: prevent wrong formatting float values by locale

### LINKED ISSUE #84: Invalid parameter value: 3037 Invalid GIS data provided to function st_geometryfromtext.
I get this error message when I do a simple insert to a Point field:
`SQLSTATE[22023]: Invalid parameter value: 3037 Invalid GIS data provided to function st_geometryfromtext. (SQL: insert into `servicos__clientes__location` (`id_user`, `id_servico_cliente`, `location`, `created_at`) values (399, 2673, ST_GeomFromText(POINT(-60,0090723 -3,0886383)), 2019-04-05 19:00:51))`

My code

`<?php

namespace NGestor\ApiFieldService\Http\Controllers\Location;

use Grimzy\LaravelMysqlSpatial\Types\Point;
use NGestor\ApiFieldService\Http\Requests\Location\SetClientePositionFormRequest;
use NGestor\ApiFieldService\Models\Location\ServicoClienteLocation;
use NGestor\ApiFieldService\Models\Service\Index\Servicos;
use NGestor\ApiFieldService\Repository\Servico\Cliente\ClienteLocation;
use NGestor\Core\Http\Controllers\Controller;

class ClienteLocationController extends Controller
{
    public function setPosition(SetClientePositionFormRequest $request)
    {
        try{

            $servico = Servicos::find($request->idServico);

            $locate = new ServicoClienteLocation();

            $locate->id_user             = $request->idUser;
            $locate->id_servico_cliente  = $servico->id_servico_cliente;
            $locate->location            = new Point($request->lat, $request->lng);
            $locate->save();

        }catch (\Exception $exception)
        {
            logger("ClienteLocationController -> setPosition ");
            logger($exception->getMessage());

            return [
                'sucesso' => false,
                'msg'     => $exception->getMessage(),
            ];
        }

        return ['sucesso' => true];
    }
}`

### PR DESCRIPTION
**Pull request by gpedro**
resolves #84
that's the right-way fix. but to avoid install ext-intl, we can just replace comma by a dot.

### CODE REVIEW

**Review by f0ntana — APPROVED** [review]

**Comment by grimzy** [comment]
Looks good and tests are passing on my machine. Any idea why they're failing on Travis: https://travis-ci.org/grimzy/laravel-mysql-spatial/builds/657630242 ?

**Comment by gpedro** [comment]
i have changed MAX_FRACTION_DIGITS from -1 to 12. reason to choose twelve:

Captura de Tela 2020-03-03 às 07 20 31

**Comment by gpedro** [comment]
all passes!
https://travis-ci.org/grimzy/laravel-mysql-spatial/builds/657701072

**Comment by grimzy** [comment]
I've delayed merging this PR because adding `ext-intl` would most likely break builds if I release a minor. I also want to avoid releasing a major and replacing a comma felt like a quick-fix (i18n-wise).

I'm going to test this out real quick: https://github.com/symfony/polyfill-intl-icu. It's already loaded when you build Laravel. This package adds `ext-intl` in composer's `suggest` and will use the PHP extension if it's already installed on the server.

**Comment by grimzy** [comment]
Thanks for fixing the tests.
I'm wondering if we're losing accuracy. Easy to test.
In any case, it doesn't seem that PHP compares floats past the 11th decimal: https://github.com/grimzy/laravel-mysql-spatial/blob/2.2.0/tests/Integration/SpatialTest.php#L351

**Comment by grimzy** [comment]
With `symfony/polyfill-intl-icu`: https://github.com/grimzy/laravel-mysql-spatial/tree/fix/locale-polyfill

**Comment by monkeyphysics** [comment]
@grimzy This week I came across a MySQL error "Invalid GIS data provided" and ultimately tracked it down to my locale rendering floats with a comma when converted to strings. Then I just saw this issue, where the bug was presumably fixed. I am on version 4.0.0.

Is the fix still pending merge? Or is this a new issue?

**Pull request closed without merging**
