### PR TITLE
Modify method of point based of laravel framework Blueprint.

### LINKED ISSUE #49: compatibility issue
Hi,

refere to `laravel\framework` commit of `Add support for defining a Spatial reference system for a Point column. (code: ddc4e05fc03a8f55a56be2afdce48ba891879d65)`, they add srid to declearation of `point` method.

Due to what I mentioned above, it needs to make point method your Blueprint compatible.

check following error:
```
Declaration of Grimzy\LaravelMysqlSpatial\Schema\Blueprint::point($column) should be compatible with Illuminate\Database\Schema\Blueprint::point($column, $srid = NULL)
```

### PR DESCRIPTION
**Pull request by enourinick**
resolves  #49

### CODE REVIEW

**Comment by J5Dev** [comment]
Any news on this being merged?

We are holding up our deployment, and if this will not be merged, we need to start to look at alternative  options.

Thank yiu.

**Comment by grimzy** [comment]
Thank you very much!

**Comment by mziraki** [comment]
any progress?!

**Comment by mziraki** [comment]
@grimzy any progress on this issue?!

**Pull request merged**
